#!/bin/bash
chk=$(cat /etc/ssh/sshd_config |grep Banner )
if echo "$chk" |grep -v "#Banner" |grep Banner > /dev/null 2> /dev/null
then
local=$(echo "$chk" |grep -v "#Banner" |grep Banner |awk '{print $2}')
if [ -f /etc/bannervps ]
then
banner=$(cat /etc/bannervps)
echo -e "\033[1;32mBanner atual\n\n\033[1;37m$banner\n\033[0m"
sleep 5
else
banner="Não há um banner no momento"
echo "De um nome ao Servidor"
read -p ":" nome
echo "Bem Vindo(a) ao Servidor $nome" > $local
echo "Digite a mensagem para seu Banner"
read -p ":" banner
echo "$banner" >> $local
echo "|P*R*O*I*B*I*D*O|" >> $local
echo "|*xTorrents*xSPAM*xDDoS*xHACKING*xFLOOD| " >> $local
echo "Informe seu Telegram para contato"
read -p ":@" telegram
echo "Entre em contato pelo Telegram @$telegram" >> $local
echo "|Config by: @judiba|" >> $local
echo "|R3V1V3R VPS|" >> $local
echo "Banner /etc/bannervps" >> /etc/ssh/sshd_config
service ssh restart > /dev/null 2> /dev/null
service sshd restart > /dev/null 2> /dev/null
fi
fi
