#!/bin/bash
echo ""
VERSION=`lsb_release -sd | cut -c 8-`
echo Versao do seu sistema operacional: ${VERSION}
echo ""
echo "Configuração de Atualização"
echo ""
echo "        BY: @judiba"
echo "        R3V1V3R VPS"
echo "        Data de criação: 15/04/2017"
echo "        Nome: PackVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
echo "Escolha o sistema da sua VPS"
echo -e "\033[1;34m
[1] Ubuntu 14
[2] Ubuntu 16
[3] Debian 7
[4] Debian 8
[5] CentOS
[6] sair \033[0m"
echo ""
read -p "Escolha o numero da sua opção: " numero

if [ "$numero" = "1" ]
then
clear
echo '-----Script By @judiba-----'
echo '--Ubuntu 14 para o Ubunutu 16--'
apt-get install update-manager-core
apt-get update -y 1>/dev/null 2>/dev/null
do-release-upgrade -d -y 1>/dev/null 2>/dev/null
wget -q https://raw.githubusercontent.com/judiba/Main/master/debian8 -O /etc/apt/sources.list
cat /etc/debian_version
echo "Atualizando a VPS..."
echo "Aguarde... "
sleep 3
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get dist-upgrade -y 1>/dev/null 2>/dev/null
apt-get autoremove -y 1>/dev/null 2>/dev/null
apt-get autoclean -y 1>/dev/null 2>/dev/null
cat /etc/debian_version
echo "O número acima mostra a versão atual do Ubuntu. É altamente recomendável que você reinicie o sistema."
read -p "Reiniciar sistema Agora? [ s/n ]: " ta
 if [ "$ta" = "s" ]
then
shutdown -r 5 1>/dev/null 2>/dev/null
clear
echo "Aguarde reiniciando..."
fi

if [ "$ta" = "n" ]
then
clear
echo " Sucesso... "
sleep 3
echo " Seu servidor foi Atualizado com sucesso! Lembre-se de reiniciar assim que possivel"
sleep 3
echo " Saindo..."
sleep 2
PackVPS
fi

fi
if [ "$numero" = "2" ]
then
clear
echo '-----Script By @judiba-----'
echo '------Para o Ubuntu 16-----'
cat /etc/debian_version
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
wget -q https://raw.githubusercontent.com/judiba/Main/master/debian8 -O /etc/apt/sources.list
echo "Atualizando a VPS..."
echo "Aguarde... "
sleep 3
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get dist-upgrade -y 1>/dev/null 2>/dev/null
apt-get autoremove -y 1>/dev/null 2>/dev/null
apt-get autoclean -y 1>/dev/null 2>/dev/null
cat /etc/debian_version
echo "O número acima mostra a versão atual do Ubuntu. É altamente recomendável que você reinicie o sistema."
read -p "Reiniciar sistema Agora? [ s/n ]: " ta
 if [ "$ta" = "s" ]
then
shutdown -r 5 1>/dev/null 2>/dev/null
clear
echo "Aguarde reiniciando..."
fi

if [ "$ta" = "n" ]
then
clear
echo " Sucesso... "
sleep 3
echo " Seu servidor foi Atualizado com sucesso! Lembre-se de reiniciar assim que possivel"
sleep 3
echo " Saindo..."
sleep 2
PackVPS
fi

fi
if [ "$numero" = "3" ]
then
clear
echo '-----Script By @judiba-----'
echo '-----Debian 7 para Debian 8'
cat /etc/debian_version
echo "Substituindo os repositorios..."
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
wget -q https://raw.githubusercontent.com/judiba/Main/master/debian8 -O /etc/apt/sources.list
echo "Atualizando a VPS..."
echo "Aguarde... "
sleep 3
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get dist-upgrade -y 1>/dev/null 2>/dev/null
apt-get autoremove -y 1>/dev/null 2>/dev/null
apt-get autoclean -y 1>/dev/null 2>/dev/null
cat /etc/debian_version
echo "O número acima mostra a versão atual do Debian. É altamente recomendável que você reinicie o sistema."
read -p "Reiniciar sistema Agora? [ s/n ]: " ta
 if [ "$ta" = "s" ]
then
shutdown -r 5 1>/dev/null 2>/dev/null
clear
echo "Aguarde reiniciando..."
fi

if [ "$ta" = "n" ]
then
clear
echo " Sucesso... "
sleep 3
echo " Seu servidor foi Atualizado com sucesso! Lembre-se de reiniciar assim que possivel"
sleep 3
echo " Saindo..."
sleep 2
PackVPS
fi

fi
if [ "$numero" = "4" ]
then
clear
echo '-----Script By @judiba-----'
echo '------Para o Debian 8------'
echo "Versão instalada"
cat /etc/debian_version
echo "Substituindo os repositorios..."
sleep 3
echo "Atualizando os repositorios..."
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
wget -q https://raw.githubusercontent.com/judiba/Main/master/debian8 -O /etc/apt/sources.list
echo "Atualizando a VPS..."
echo ""
sleep 3
echo "Aguarde... "
sleep 3
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get dist-upgrade -y 1>/dev/null 2>/dev/null
apt-get autoremove -y 1>/dev/null 2>/dev/null
apt-get autoclean -y 1>/dev/null 2>/dev/null
echo "Versão Atualizada"
cat /etc/debian_version
echo "É altamente recomendável que você reinicie o sistema."
read -p "Reiniciar sistema Agora? [ s/n ]: " ta
 if [ "$ta" = "s" ]
then
shutdown -r 5 1>/dev/null 2>/dev/null
clear
echo "Aguarde reiniciando..."
fi

if [ "$ta" = "n" ]
then
clear
echo " Sucesso... "
sleep 3
echo " Seu servidor foi Atualizado com sucesso! Lembre-se de reiniciar assim que possivel"
sleep 3
echo " Saindo..."
sleep 2
PackVPS
fi

fi
if [ "$numero" = "5" ]
then
clear
echo '-----Script By @judiba-----'
echo '------Para o CentOS 6.8------'
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
wget -q https://raw.githubusercontent.com/judiba/Main/master/debian8 -O /etc/apt/sources.list
echo "Atualizando a VPS..."
echo "Aguarde... "
sleep 3
apt-get update -y 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get dist-upgrade -y 1>/dev/null 2>/dev/null
apt-get autoremove -y 1>/dev/null 2>/dev/null
apt-get autoclean -y 1>/dev/null 2>/dev/null
cat /proc/version
echo "O número acima mostra a versão atual do CentOS. É altamente recomendável que você reinicie o sistema."
read -p "Reiniciar sistema Agora? [ s/n ]: " ta
 if [ "$ta" = "s" ]
then
shutdown -r 5 1>/dev/null 2>/dev/null
clear
echo "Aguarde reiniciando..."
fi

if [ "$ta" = "n" ]
then
clear
echo " Sucesso... "
sleep 3
echo " Seu servidor foi Atualizado com sucesso! Lembre-se de reiniciar assim que possivel"
sleep 3
echo " Saindo..."
sleep 2
PackVPS
fi

fi
if [ "$numero" = "6" ]
then
clear
echo "Saindo..."
sleep 3
exit
fi
